<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="MediatR" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Serilog" />
	</ItemGroup>
</Project>
