apiVersion: v1
kind: Service
metadata:
  name: pgbouncer
  namespace: transaction-aggregation
  labels:
    app.kubernetes.io/name: pgbouncer
    app.kubernetes.io/part-of: transaction-aggregation
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: pgbouncer
  ports:
    - name: postgres
      port: 6432
      targetPort: postgres
      protocol: TCP
