apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-data
  namespace: transaction-aggregation
  labels:
    app.kubernetes.io/name: keycloak
    app.kubernetes.io/component: identity
    app.kubernetes.io/part-of: transaction-aggregation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
