apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: grafana-data
  namespace: transaction-aggregation
  labels:
    app.kubernetes.io/name: grafana
    app.kubernetes.io/component: monitoring
    app.kubernetes.io/part-of: transaction-aggregation
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
