<Project Sdk="Microsoft.NET.Sdk.Web">
	<PropertyGroup>
		<DockerComposeBuildEnabled>false</DockerComposeBuildEnabled>
	</PropertyGroup>
	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Mvc.ApiExplorer" />
		<PackageReference Include="AspNetCore.HealthChecks.NpgSql" />
		<PackageReference Include="AspNetCore.HealthChecks.Redis" />
		<PackageReference Include="AspNetCore.HealthChecks.UI.Client" />

		<PackageReference Include="Microsoft.AspNetCore.Mvc.Versioning" />

		<PackageReference Include="Microsoft.EntityFrameworkCore.Tools">
			<PrivateAssets>all</PrivateAssets>
		</PackageReference>

		<PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" />

		<PackageReference Include="Serilog.AspNetCore" />
		<PackageReference Include="Serilog.Sinks.Console" />
		<PackageReference Include="Serilog.Sinks.Seq" />

		<PackageReference Include="Microsoft.AspNetCore.OpenApi" />
		<PackageReference Include="Scalar.AspNetCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TransactionAggregation.Application\TransactionAggregation.Application.csproj" />
		<ProjectReference Include="..\TransactionAggregation.Infrastructure\TransactionAggregation.Infrastructure.csproj" />
		<ProjectReference Include="..\TransactionAggregation.Persistence\TransactionAggregation.Persistence.csproj" />
		<ProjectReference Include="..\TransactionAggregationAPI.ServiceDefaults\TransactionAggregationAPI.ServiceDefaults.csproj" />
	</ItemGroup>

</Project>