<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Bogus" />
		<PackageReference Include="Microsoft.Extensions.Caching.StackExchangeRedis" />
		<PackageReference Include="Microsoft.Extensions.Http" />
		<PackageReference Include="Polly" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TransactionAggregation.Application\TransactionAggregation.Application.csproj" />
	</ItemGroup>

</Project>