<Project Sdk="Microsoft.NET.Sdk">
	<ItemGroup>
		<PackageReference Include="Mapster.DependencyInjection" />
		<PackageReference Include="MediatR" />
		<PackageReference Include="Mapster" />
		<PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
		<PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Logging.Abstractions" />
		<PackageReference Include="Microsoft.Extensions.Options.ConfigurationExtensions" />
		<PackageReference Include="Serilog" />
		<PackageReference Include="Microsoft.EntityFrameworkCore" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\TransactionAggregation.Domain\TransactionAggregation.Domain.csproj" />
	</ItemGroup>

</Project>