<Project>

	<!--Central Package Management -->
	<PropertyGroup>
		<ManagePackageVersionsCentrally>true</ManagePackageVersionsCentrally>
		<CentralPackageTransitivePinningEnabled>true</CentralPackageTransitivePinningEnabled>
	</PropertyGroup>

	<!--Common .NET Settings -->
	<PropertyGroup>
		<TargetFramework>net10.0</TargetFramework>
		<ImplicitUsings>enable</ImplicitUsings>
		<Nullable>enable</Nullable>
	</PropertyGroup>

	<!--Build & Code Quality -->
	<PropertyGroup>
		<TreatWarningsAsErrors>false</TreatWarningsAsErrors>
		<!-- turn true in CI -->
		<WarningsAsErrors />
		<AnalysisLevel>latest</AnalysisLevel>
		<EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
	</PropertyGroup>

	<!--Versioning (optional but recommended) -->
	<PropertyGroup>
		<Version>1.0.0</Version>
	</PropertyGroup>

	<!--Common Usings (applies to all projects) -->
	<ItemGroup>
		<Using Include="System" />
		<Using Include="System.Collections.Generic" />
		<Using Include="System.Linq" />
		<Using Include="System.Threading" />
		<Using Include="System.Threading.Tasks" />
	</ItemGroup>

</Project>