<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<RootNamespace>Modules.Transactions.Domain</RootNamespace>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="MediatR" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\..\..\BuildingBlocks\SharedKernel\SharedKernel.csproj" />
	</ItemGroup>

</Project>