// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Modules.Customers.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Modules.Customers.Infrastructure.Migrations
{
    [DbContext(typeof(CustomersDbContext))]
    partial class CustomersDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("customerdirectory")
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Modules.Customers.Domain.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Customers", "customerdirectory", t =>
                        {
                            t.HasCheckConstraint("CK_Customers_Name_NotBlank", "btrim(\"Name\") <> ''");

                            t.HasCheckConstraint("CK_Customers_Reference_Format", "\"Reference\" ~ '^[A-Za-z0-9][A-Za-z0-9_-]*$'");
                        });
                });

            modelBuilder.Entity("Modules.Customers.Domain.Customer", b =>
                {
                    b.OwnsMany("Modules.Customers.Domain.LinkedAccount", "Accounts", b1 =>
                        {
                            b1.Property<Guid>("CustomerId")
                                .HasColumnType("uuid");

                            b1.Property<string>("Institution")
                                .HasMaxLength(50)
                                .HasColumnType("character varying(50)");

                            b1.Property<string>("ExternalAccountId")
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)");

                            b1.Property<DateTime>("LinkedAt")
                                .HasColumnType("timestamp with time zone");

                            b1.HasKey("CustomerId", "Institution", "ExternalAccountId");

                            b1.ToTable("CustomerAccounts", "customerdirectory", t =>
                                {
                                    t.HasCheckConstraint("CK_CustomerAccounts_ExternalAccountId_NotBlank", "btrim(\"ExternalAccountId\") <> ''");

                                    t.HasCheckConstraint("CK_CustomerAccounts_Institution_Format", "\"Institution\" ~ '^[A-Za-z0-9][A-Za-z0-9_-]*$'");
                                });

                            b1.WithOwner()
                                .HasForeignKey("CustomerId");
                        });

                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
